title: Web Mapping in Jekyll # Your website title
author: Hello World # change this to your name
email: helloworld@mail.com # chnage this to your email
description: >- # this means to ignore newlines until "baseurl:"
  A leaflet map in Jekyll
baseurl: ""
url: ""
port:
google_analytics: UA-000000000-0
markdown: kramdown
# remote_theme: "wslerry/web-mapping"
# theme: web-mapping

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

exclude : [
  ".gitignore",
  "LICENSE.txt",
  ]
