title: Web Mapping in Jekyll # Your website title
author: Hello World. # change this to your name
email: helloworld@mail.com # chnage this to your email
description: >- # this means to ignore newlines until "baseurl:"
  A leaflet map in Jekyll
baseurl: ""
url: ""
port: 4001
google_analytics: UA-000000000-0
markdown: kramdown
# remote_theme: "wslerry/web-mapping"
theme: web-mapping

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - github-pages

exclude : [
  ".gitignore",
  "Gemfile",
  "Gemfile.lock",
  "web-mapping.gemspec",
  "README.md",
  "LICENSE.txt",
  "examples"
  ]
